---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/namespace.json
apiVersion: v1
kind: Namespace
metadata:
  name: danger-million
  labels:
    security: restricted
    educational: "true"
