---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: listen
  namespace: argocd
  labels:
    chartVersion: &chartVersion 4.3.0
spec:
  destination:
    namespace: aiml
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: &url https://github.com/GoodMannersHosting/home-enterprise-labops.git
      targetRevision: &branch main
      path: kubernetes/services/listen
    - repoURL: *url
      targetRevision: *branch
      ref: values
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: *chartVersion
      helm:
        valueFiles:
          - $values/kubernetes/services/listen/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
