---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volsync
  namespace: argocd
  labels:
    snapshotControllerChartVersion: &snapshotControllerChartVersion 5.2.0
    volsyncChartVersion: &volsyncChartVersion 0.16.9
spec:
  destination:
    namespace: volsync
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/GoodMannersHosting/home-enterprise-labops.git
      targetRevision: main
      ref: values
    - repoURL: ghcr.io/piraeusdatastore/helm-charts
      chart: snapshot-controller
      targetRevision: *snapshotControllerChartVersion
      helm:
        valueFiles:
          - $values/kubernetes/core/volsync/snapshot-controller.values.yaml
    - repoURL: ghcr.io/home-operations/charts-mirror
      chart: volsync-perfectra1n
      targetRevision: *volsyncChartVersion
      helm:
        valueFiles:
          - $values/kubernetes/core/volsync/volsync.values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
