# Replace this file with the output of:
# read -s clientsecret # paste the client secret here
# kubectl create secret generic argo-workflows-sso -n argo \
#   --from-literal=client-id=argo-workflows \
#   --from-literal=client-secret=${clientsecret} \
#   --dry-run=client -o yaml | \
#   kubeseal --cert keys/sealed-secret.crt -oyaml \
#     -{f,w}=kubernetes/core/argo-workflows/oidc-secret.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgBy3Vy6S5HrQlbm5X20pFd01IfMzULJqr9Y56Rj6g/pwiRPV7RlqW/TMM2wOQZi/RgbCSl1sEhqIm5duL/TavueaA7ySayFm0A6EtF2q2oCLQtz6Ak3ySApQrV8ANtazbVpmJxi6QIOw2D3e2m42uw6H1PXQ7aiccVem7zSBPhSohtAU/1R6bNbu1SBfLKoj1z+BxPm2ckrXVgHNoPHF4lI46cgPCf3KhRpVCViErYt7At79jy4XTkImAUPeP1yZbgoIy2NrCrNpg/rVAJNlu0wnjfqj4Uy4ytSqrXvWT4xQ3omq3e87ENOMo/J5JEsqWA/nLd+1JAGx33NKUJOS7twHN4R7FKCK35MaMWtjmQYCXoJlZOF1kL/CTl29/1AE8KgWdVKmK+YGiMjFX6jaELjMndGuiw0QfKif4V+G57wuc3x/J2v4zEAzhOXKqJrhLOZigcBgtC7FIA933+gcEC8SXZD3qGTq5OW/VpmpI784cewz3M8q/52ElhHIa6NCguari2vEGOm0CIX+A+glzTVSICSzdMK6FZSzlUp8hUe9qzNAV1mJyv1Ve9zU4Dy2aIDzL1e6fSYf82vpAVwMk9ESFzkpn6NV1U6H1TieGxobuUq71/HqzMF6+l+E8WhsEVAl28arM9fIfFCNWARmkcQaQZ4Y7yfWCHZwaBYq3potvTVZ/gqB+aV+eo50EfW6XOcI1XLGPDcAtmj3MujQQ==
    client-secret: AgBwr9Tpi12zZ7YjQvUm/Lm+QO1BZ1pPKpdzERM4A1BPvW0uSXRqaj0sx1gjvOpwfhc6HhYW7yJZWh59NqKihl3IStZyy/eDK2Z1kSIjWSNadR76wAfUvTK7gMORSK3wG4jxqnu9f7/a7ckFNfvCMMY3aDqpVilyZNH1lxRGYWECbDJPT3Z9JMwdq3KF1Agb+Ico7CAdw3eRg5SgdEpC20mXnnjGTL5AbBCAYHxgwpzCmtllg0PpfAM7NK5OQx7xZV/y+0sKs9/IZVKd+ureBkEPtTfp6rTAaTC4wRIj8UQW6J1auGistN0UiMbJp7r1V0w5VjrRphSueBNq6OavvQmxKjj63dASs6zrS2umTpDEZDTR+ufionb3gzY0s/0pF5LsBBoMYIZU+O8KpcQZMhmxLiKvg2Eyjl2Pu5nX/JOtC9VN/UAcUv9gSuVS69dhW7mOtmQR3cbTz3cv5hMy4xraThOZKEqjP/87ZtPVJMh4yvsZvVRRb4Hx7pABvaXiEVGWdF2TaWHxH7gLOOXtxg8y6XhUR8EkageT6EBg2yrGgRcIkz8JYH9zNpKPT6xX1fHp2R1int8Cq1QIZCRxxppT2vs71rRFaDtmxP5FO3q1CBIJSrHobTPDfQCfC3200Sj9hlQp9w3sIu6fA+O+gd/gRM7L4VztEnXqGJN+ohPi3aQ6g8a/WcRbOto+e+eqX+RN28nyOUuYmDlkuiTQHEkZUWME4o8BEJPChDGHk9o5xw==
  template:
    metadata:
      name: argo-workflows-sso
      namespace: argo
