---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cicd

resources:
  - webhook-example/workflow-sa.yaml
  - webhook-example/workflow-template.yaml
  - webhook-example/workflow-event-binding.yaml
  - webhook-example/webhook-client-rbac.yaml
