---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cicd

resources:
  - webhook-example/workflow-sa.yaml
  - webhook-example/workflow-executor-rbac.yaml
  - webhook-example/workflow-template.yaml
  - webhook-example/workflow-event-binding.yaml
  - webhook-example/webhook-client-rbac.yaml
  - golang-samples-build/storage-conf.yaml
  - golang-samples-build/service-account.yaml
  - golang-samples-build/rbac.yaml
  - golang-samples-build/workflow-template.yaml
