---
apiVersion: v1
kind: ConfigMap
metadata:
  name: buildah-storage-conf
  namespace: cicd
data:
  policy.json: |
    {
      "default": [{"type": "insecureAcceptAnything"}],
      "transports": {
        "docker-daemon": {"": [{"type": "insecureAcceptAnything"}]}
      }
    }
  registries.conf: |
    unqualified-search-registries = ["docker.io"]
  storage.conf: |
    [storage]
    driver = "overlay"
    runroot = "/storage/run/containers/storage"
    graphroot = "/storage/.local/share/containers/storage"
    rootless_storage_path = "/storage/.local/share/containers/storage"
    [storage.options]
    pull_options = {enable_partial_images = "true", use_hard_links = "false", ostree_repos=""}
    [storage.options.overlay]
