---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: artifact-keeper-database-credentials
  namespace: artifact-keeper
spec:
  encryptedData:
    password: AgBQttfVsLgGcZpEGiOoOFui3QvPonaQXaCnFjz7XE2l0njqKmSTsumZeh8/fkb//+dv3G+IL7wRCfBVIsV6hhqAML5txov1Cq9OgrHfPse/505UepjIyZvxGBsps7d42iECUsLcOKOV1PsXGRN4PKnbPS5uVDooWvjB+4XwDgncVCMX3s4DU3k4ffRtSC/RAiyOc/7qZygnCc/neLls62Vuhqw9llMWjbyEV0NI39Gap5Xx4EEgUHx0KpWoHd9dI+uQ4UdhTx/5PHhIJnAQVQpUBT9twZCgUNwdIUQsdpO86VQv+54/WGVzxOdAzO96zJwMDM8M2HZCLIhLGce2dxbiZHZiAUTnKfWYCJldjUS/nZJesoxTUQERtoQYLrq7wZ1poPKofNq8AcjEkHliQ68nDMPrl3OErUwHcnatHg+eJm6TQfg7xXeTjqlfYNJwdFbSRZlsbwxt3T1+wgfMctV3MBGGw99fOQM6ue3vIqdFdSzjcs73WwUVSwDayrHzw7F3x8TqN1k/uhlRc/+m+Cr3s9PQF88y6UDS2ocWuC7viryUsJhjln5zOk4K8yimcXDQkXdFSdmq8rJ6cUH/kOARKZixA8qH5Zy9BYTHjdqnnCk/P5jBBx4agB8jf6oh8he9iKLUlZ1m8aj0UQinFB/QnU/w77zFnHgImhAwI2tVPeUOykFgt8Fq4xxKkyOLSLaKvyVRxC/jNaD9HQSfhW0to/GKB7j+Hc9bK7XY89YXKj61+ehCTbGGiGxQXg==
    username: AgB9MdpXb3urYJ4rhpJZuQt2t5SZ+yVsPQZI1l4Q8/JMBCD+vlDt3ph1ROCRr3JOutFcD3qoQpkhoZAXkdS4Wndxa6jyKawXq05k/PIu+MlvjXHkCnHc0iqsFZihRAusf6INTPR6hQLuFnfrUM9IOer/bBV5Vep/p+R3KsE8Y9VhhwyUtswUQBFtCZlRZ0R5mjmGnFO+AnJ5G20LFWImKMz1SWjELoDj4s9xQ7uJtuw8LLrPlcRans8s2vRtPzaRhwL4orswQGC/7an4NyE6l2BmtDtHaxoEV9/Gj5QhHTHOn2zllaJZArsok6De5+Jcow4LeevMwTV9/cdxD6I/v+KcL6UWEHNW8ZWvf88VUaMGwoFEM/Mtk+nerM3Wn4FaEGBKST9xCTabzbnLyCXW9D4ytceR7wsOVjacyaiToMsehwoqdcZlmhEMutsShs+J0uj+ubw9yziKmm4w4g+OzCUXUlxPnx6Ut0UMKHxmQ5Q/+/jcMZ1mwZzxHV80O1gs0KcugjuPiyQS+NQsTOhyWH5vh7BwAQDmQ4f23YaOj9jrAV2l/1nwhPpU1PPfDzLTZEgwGVbgNH5S0QEDZN6Fclx7KY0Ljdq1ENk097lUmBp8cnrxZrDfkrxeKB5pMtvLz7NSTx7qOpvs4z3tkVQyuAZmwXMfUZSncxXNu+ODPnh+mp/Lom0NLSWIqrDdsggCHvKw3bhYUJ0v73kCva08zGdK
  template:
    metadata:
      name: artifact-keeper-database-credentials
      namespace: artifact-keeper
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: artifact-keeper-jwt-secret
  namespace: artifact-keeper
spec:
  encryptedData:
    jwt-secret: AgAYSVFHSgxtgUEg0klUnJy0bf11tFcwChYgvDNPvkIpsmMfxS5kqGyEq45Ui5d4GY0bJI9yNZt5bStcico6CG6P9cjIFSL2hAUsTmltpYfPTUpkzvdyUqcfkB+tBfqHARIo8SZw6ImOC/ZL9CEb9obdWmHJnNKQiC+siIPiMVqP6W388H0sRFL/0/bZ6Qsj46Q4tl4DvVEsOAR91PG4MHAqAhRYjrUPNGDHokfQpaHbjxZxrczu3mX+lYagnLMe9VkqVVgbpfKlPn5N6tdsfDnPX8QaQyoYoCVnE6z+xyqzPZ7lWYx6gqxei52IaGvPcUmS/FjASEjFm1D0dIgJttyoF5MyQK2HUZ5VIL1tKL1nx81tmUebFYc0Qyf/LlEoBipnaivEFZPsi8PsojYTaYstb3ZPN7e5/CqL5OD8wutR4JsHCdJez0Velxj3UU67Pn/w4dWuQqZH5HorwlHem00K6uvCMBUVm3ox21U2SHXiCJWMGzVzvyH55tXPW9XvMVw783sriZ1Wn/aYx/dZEQk3qFyEnw1Ts+ZuaTOIIqXfGQU0IjwvxY1R07XTO0HC3XK5aJ+Sm+PjjZPepN8H4c7yNrH9yOoBe6LieXIiKYSJi3tsTkIqtAiVqOqWgCAsz+AQHRHZ0amCwj+kHcD7uABcohzM1SIH7H6cRPBa9OiAynm8REJHxIq7Ikp2JdCwuR2sNZWSqQu5OcdAoV++pCECqjxpWevlEeagRJQspG9n/ngDGUfZIg2KElyL3q0GqNnTYcXx6fQYvceyNIHQkkez
  template:
    metadata:
      name: artifact-keeper-jwt-secret
      namespace: artifact-keeper
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: artifact-keeper-admin-password
  namespace: artifact-keeper
spec:
  encryptedData:
    password: AgAfoXTjyFR48AXr5zDaxGtXIj9QN/41LGB/blfKto117NKxzpcOX/FGaYNuoVCoLUtOwO+pnQlSnB674DRQ1yHlPsM7HYjXhfWX5eIGDGXCxcEqjb90jjLThRxrRe6cTAv7QZXjOsD+D8+dkRCeFbVv2yjZo7CJczZKSjeFtUNLAQXQ68BwAM/OG8J78qcggFq4IbUvYiVkw4W4F7Xo7Jcx5pOllfUB/bjqf/ndAVGM++0nWaQyd088vYarZ7RY0WmfCDLWcN97B8qu8Zab4Stau3Wh6UKHClODmmH6pP+1d6fzPGk0W3rH5RZaCLqUtB2tgMfQOguaf2f0HRTFfiPgfloKnH5kka6aa9rwaMlfDSrwKS/T9VcwKlgkT22grCeFxDEqw0LHu0KSAGnHS7mjT2581opW/l2ARsmJ/eLi+blMLouQt+mAeKQNZvvv7JhVEDAO8VftLiXMQrZCmS+4kdDF3mDE8k4oWkB9eJxVkwdMArOXXc/C86BcpqdcWVBSMURbSS4FcXWr4bS43mOE1zDL0OBcQVCEzWg7Vnuus60FsKX1d3Jt66c+y6L2OiSMCbmHBbvBMywMfXGNcsuqDljpTIQMGcNNrLp/Vhz1wh/7G/skv/u1LDRMuqIgpZbRWk4UagVMFIIdaqZW7BTytnITfkJqE1Niv9/q1llyz2uxxo0TE1Ho5gLHDmpOwsz1uO8XE3wfJznnR6TiBYOOWWqlGYZ5oxZxFMJXBnr+Rz4OOoo9Cam7mV7rBg==
  template:
    metadata:
      name: artifact-keeper-admin-password
      namespace: artifact-keeper
    type: Opaque
