---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: artifact-keeper-meilisearch-credentials
  namespace: artifact-keeper
spec:
  encryptedData:
    masterkey: AgAKIh6DwufM/G93qsBrNR7lKjlRTdGWLn0RaofLZxKYpoSRyGq1hmaAT+uOiS7SBDLlvvvssDnUsxuwzH9PtnSOylybYi2+IsT0dvt06I1XSrEcB6g/LcnKapxUj3pvunSMqzPf9uzO0Zll/AjTLVE86pgFxgtWz+yY8FEcvVQe/lJ8g3rUdcLVF60AxN9bW7P+ziFBWKmOfE1Di1boRAVCwmkwl8rxSQHFouVqzUXODfA8sG9c8ENlhYVSeuuTg/40psERJwoCtDk0YTeFY97OzsmVI1K/4ZP1zSFQDw82vX6hB34zOwTGTStFH91p6bVc24zOOTeYvdbbQvwmKww2mnjUjNEvYw+iyFM8xsc2aviWK8ntePvQeBT/Y0a7Fe8Qaq8ZD3lTaLkNGgzFm8X/X5lSADNruh0MANZLSb3bQwo55tvzq0c+ptfhmCE/06eWaec4n+2IUPPC2A+pLyWAMbS7Mjt/mO78FR0G/GfRKUbuWQjiONZNLtLWW0VdH2qXdL/nJmAA8I1EEoPHjob2YvDove+AM5n/0IjJzQ57hz+IV6e7k/Wft1FbpH8KWuIQx6//ZH7MnlPVWOnUfxOwQTQi/+T+Qo6yS1Q35OXfd9+82ZlPbyOVN4/I91OmzMfl2lXCowzmLX9r1YRNEDQQk6DK2rYM3L4tOpUh8zAcLmsCDHc/VPvjSdvNlYXAE4tnBXlkmuIIo9l/QF11vmwrrC+lzPyBMl7Hy3ONNoVzOvzZxul6GqzP7II4yg==
  template:
    metadata:
      name: artifact-keeper-meilisearch-credentials
      namespace: artifact-keeper
    type: Opaque
