apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - CiliumBGPAdvertisement.yaml
  - CiliumBGPClusterConfig.yaml
  - CiliumBGPPeerConfig.yaml
  - CiliumL2AnnouncementPolicy.yaml
  - CiliumLoadBalancerIPPool.yaml
